title: Sarah Fritz
email: sarah.fritz@iwh-halle.de
description: Welcome to my website!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
header_pages:
  - index.md
  - research.md
  - teaching.md
  - cv.md
